channels:
  - conda-forge
  - defaults
dependencies:
  - ipyleaflet
  - numba
  - requests
  - numpy
  - rasterio
  - tqdm
  - affine
  - scipy
  - Pillow
  - matplotlib
  - ipywidgets
  - xarray
  - pyproj
  - branca
  - pydap
  - dask
  - lxml
