channels:
  - conda-forge
  - defaults
dependencies:
  - ipyleaflet
  - numba
  - requests
  - numpy
  - rasterio
  - tqdm
  - affine
  - scipy
  - Pillow
  - matplotlib
  - ipywidgets
  - xarray
  - pyproj
  - branca
  - pydap
  - dask
  - lxml
  - zarr
  - intake
  - intake-xarray
  - dask-kubernetes
  - cython
  - scikit-image
  - shapely
  - pip:
    - soupsieve
    - gcsfs
